### ISSUE TITLE
Slack notification Error on removing images when image is being used twice in compose file.

### ISSUE THREAD

**Issue by mindrunner** [containrrr/watchtower#387]
**Describe the bug**
I have a docker compose file with multiple containers. Two of them use exactly the same image with a different entrypoint. After watchtower update, while removing images, it tries to remove the image twice. Second attempt apparently fails.

**To Reproduce**
1. start a compose setup with mutiple containers sharing the same image
2. start watchtover 
3. enable notifications (slack, email, etc)
4. See error in slack channel

(This is probably not related to the slack notification itself, but was only tested with this type of notification)

**Expected behavior**
No errors

**Screenshots**
![screenshot_20191006_154051](https://user-images.githubusercontent.com/1413542/66276433-42f6a980-e850-11e9-9338-55a420ba42c7.png)

**Environment**
 - Ubuntu 18.04 LTS
 - amd64
 - Docker version 19.03.2, build 6a30dfc
(Probably unrelated information)

**Logs from running watchtower with the `--debug` option**
Will provide, if we really need them.

**Comment by simonaronsson** [comment]
Thank you for the report 🙏 

From what I can tell, no additional harm is done other than receiving a false positive. Does this match with your observation? A nice solution to this would be to put all images flagged for removal into an array and then deduplicate them before deletion after all container updates have finished.

Feel free to have a stab at it, I'd be happy to provide code review and guidance.

**Comment by mindrunner** [comment]
Hi @simskij 

thank you for your answer and taking your time. Firstly, yes I can confirm, that this is likely to be only a cosmetic issue.

Secondly, I have to say, I am not a go developer and I struggled to get the code running to proper test my fixes.
 - Can debug in the IDE
 - Cannot get the golang-app in Docker running. I am always getting
`standard_init_linux.go:211: exec user process caused "no such file or directory"
` when starting the container.

Thus, my code is rather untested. 

PR here:
https://github.com/containrrr/watchtower/pull/393

I am using an external library to be able to use a Set data structure (Go still does not seem to provide one). While restarting the containers, instead of deleting an image, I put the container to a set-instance. After everything is done, all images, associated to the in-set-containers are going to be deleted.

**Comment by simonaronsson** [comment]
This should be solved by your PR (#393) in v0.3.10.
Do you share that observation?

**Comment by mindrunner** [comment]
It should be solved, but I have no setup running to confirm this at the moment. Give me a couple of days. I will try to reproduce it so we can be sure the problem does not exist anymore! :)

**Comment by mindrunner** [comment]
NACK

Still getting the errors with tag `latest`. Cannot figure out how to check the version string. `watchtower` seems to not support a `-V` or `-v` parameter.

I remember I was testing it with the first version of my PR, but not with the second one. Also my test looks different now, but that should not matter. Any idas what might be going on?

**Comment by simonaronsson** [comment]
I've moved the code around a bit and switched the map to contain image ids instead of containers.
I also added some tests to make sure it works. It does not break for me. Mind checking out master and trying it out?

**Comment by mindrunner** [comment]
`master` means `latest` tag on docker-hub?

**Comment by simonaronsson** [comment]
Oh, sorry. No, with master I was referring to checking out the repo and building it. 😄 
If that's too much of an effort, I'll try to solve it some other way 👍

**Comment by mindrunner** [comment]
`docker build . -f dockerfiles/Dockerfile.dev-self-contained`
fails with
```
.
.
.
go: directory go/pkg/mod/gopkg.in/tomb.v1@v1.0.0-20141024135613-dd632973f1e7 outside available modules
go: directory go/pkg/mod/gotest.tools@v2.2.0+incompatible outside available modules
go: directory go/pkg/mod/gotest.tools@v2.2.0+incompatible/assert outside available modules
go: directory go/pkg/mod/gotest.tools@v2.2.0+incompatible/assert/cmd/gty-migrate-from-testify outside available modules
go: directory go/pkg/mod/gotest.tools@v2.2.0+incompatible/assert/cmp outside available modules
go: directory go/pkg/mod/gotest.tools@v2.2.0+incompatible/assert/opt outside available modules
go: directory go/pkg/mod/gotest.tools@v2.2.0+incompatible/env outside available modules
go: directory go/pkg/mod/gotest.tools@v2.2.0+incompatible/fs outside available modules
go: directory go/pkg/mod/gotest.tools@v2.2.0+incompatible/golden outside available modules
go: directory go/pkg/mod/gotest.tools@v2.2.0+incompatible/icmd outside available modules
go: directory go/pkg/mod/gotest.tools@v2.2.0+incompatible/icmd/internal/stub outside available modules
go: directory go/pkg/mod/gotest.tools@v2.2.0+incompatible/internal/difflib outside available modules
go: directory go/pkg/mod/gotest.tools@v2.2.0+incompatible/internal/format outside available modules
go: directory go/pkg/mod/gotest.tools@v2.2.0+incompatible/internal/maint outside available modules
go: directory go/pkg/mod/gotest.tools@v2.2.0+incompatible/internal/source outside available modules
go: directory go/pkg/mod/gotest.tools@v2.2.0+incompatible/poll outside available modules
go: directory go/pkg/mod/gotest.tools@v2.2.0+incompatible/skip outside available modules
go: directory go/pkg/mod/gotest.tools@v2.2.0+incompatible/x outside available modules
go: directory go/pkg/mod/gotest.tools@v2.2.0+incompatible/x/subtest outside available modules
The command '/bin/sh -c cd /watchtower &&     GO111MODULE=on CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static"' . &&   GO111MODULE=on go test ./... -v' returned a non-zero code: 1
```

**Comment by mindrunner** [comment]
Sure, no worries. I am on it!

**Comment by mindrunner** [comment]
Works perfectly fine now :)

**Comment by simonaronsson** [comment]
Yay! I'll make sure that it's included in 0.3.11 🙏

**Comment by EnOane** [comment]
@simskij hello, are u include this pull to 0.3.11??

**Comment by simonaronsson** [comment]
> @simskij hello, are u include this pull to 0.3.11??

Yes, that's my ambition! 😅
